### ISSUE TITLE
Missing `greenways-logo.png`

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/platform#447]
It seems like we are missing that image file, thus we are gettings the following error on our webpage for `develop-0.7.0` branch:

`"NetworkError: 404 Not Found - http://localhost:8000/static/dist/images/greenways-logo.png"`

I see that we are referencing that file in our `_header.scss` file here:

```css
#site-header {
    background: url(images/greenways-logo.png);
    position: relative;
    z-index: 99;
    padding: 0.5em;
    box-shadow: 0 0.125em 0 $opacity-low-black;
}
```

Unless I am missing something, we should probably check that image file into our repo.
